server:
  port: 8001
  runMode: debug
logger:
  filePath: ../logs/logs.log
  encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: Mohammad1367
  database: pecalets
  sslMode: false
redis:
  host: localhost
  port: 6379
  password: Mohammad1367
  database: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240
